function ROIImageInfoNew=Interp_ROIImage(ROIImageInfo, ProgramPath, ROIImageInfoNew, BoxKernelFlag)
%Prepare files and pad image
[SrcImgFile, DesImgFile]=Interp_GenerateResampleTempFileJoy(ROIImageInfo, ProgramPath);

%Reformat
FlipRowFlag=0;
Interpolation3D_Uint16(SrcImgFile, DesImgFile, ...
    single(ROIImageInfo.XPixDim), single(ROIImageInfo.YPixDim), single(ROIImageInfo.ZPixDim), ...
    uint16(ROIImageInfo.XDim+2), uint16(ROIImageInfo.YDim+2), uint16(ROIImageInfo.ZDim+2), ...
    single(ROIImageInfo.XStart-ROIImageInfo.XPixDim), ...
    single(ROIImageInfo.YStart-ROIImageInfo.YPixDim), ...
    single(ROIImageInfo.ZStart-ROIImageInfo.ZPixDim), single(0), ...
   single(ROIImageInfoNew.XPixDim), single(ROIImageInfoNew.YPixDim), single(ROIImageInfoNew.ZPixDim), ...
    uint16(ROIImageInfoNew.XDim), uint16(ROIImageInfoNew.YDim), uint16(ROIImageInfoNew.ZDim), ...
    single(ROIImageInfoNew.XStart), single(ROIImageInfoNew.YStart), single(ROIImageInfoNew.ZStart), FlipRowFlag, uint16(BoxKernelFlag));

%Update ROIImageInfo
ROIImageInfoNew=Interp_UpdateROIImageInfo(ROIImageInfoNew, DesImgFile);
delete(SrcImgFile);
delete(DesImgFile);