function SaveSelectROI_Outside(TxtFile, NewROI, SelectOrgan)

%---Read file
RowNum=length(SelectOrgan);
IndexBegin=[]; IndexEnd=[];

for i=1:RowNum
    %---Data block IndexBegin+1:IndexEnd-1
    IndexTemp=strmatch(['//  Beginning of ROI: ', SelectOrgan{i}], TxtFile, 'exact');
    IndexBegin=[IndexBegin; IndexTemp];
    
    IndexTemp=strmatch(['}; // End of ROI ', SelectOrgan{i}], TxtFile, 'exact');
    IndexEnd=[IndexEnd; IndexTemp];
end


MeshCell={'surface_mesh={'; ...
    'allow_adaptation = 1;'; ...
    'replace_mean_mesh = 0;'; ...
    'auto_clean_contours = 1;'; ...
    'auto_smooth_mesh = 1;'; ...
    'internal_weight = -3.000000;'; ...
    'surface_weight = 1.000000;'; ...
    'distance_weight = 2.000000;'; ...
    'profile_length = 10;'; ...
    'limit_feature_search_string: Full'; ...
    'pixel_size = 1.000000;'; ...
    'feature_weight = 0.010000;'; ...
    'lower_CT_bound = 0.000000;'; ...
    'upper_CT_bound = 4095.000000;'; ...
    'gradient_clipping: Soft'; ...
    'gradient_direction: Unsigned'; ...
    'maximum_gradient = 100.000000;'; ...
    'avoid_CT_range: None'; ...
    'avoid_CT_threshold = 4095.000000;'; ...
    'number_of_modes = 0;'; ...
    'number_of_vertices = 0;'; ...
    'number_of_triangles = 0;'; ...
    'max_iterations = 10;'; ...
    'smooth_between_iterations = 0;'; ...
    'repair_between_iterations = 1;'; ...
    'translation_increment_cm = 0.500000;'; ...
    'rotation_increment = 20.000000;'; ...
    'magnify_increment = 0.200000;'; ...
    'sphere_tool_radius = 1.500000;'; ...
    'gaussian_tool_radius = 3.000000;'; ...
    'vertex_drag_curvature = 0.700000;'; ...
    'vertex_drag_neighbor_layers = 3;'; ...
    'vertices={'; ...
    '};  // End of vertices for surface mesh'; ...
    'triangles={'; ...
    '};  // End of triangles for surface mesh'; ...
    '}; // End of surface_mesh'; ...
    'mean_mesh={'; ...
    'samples = 0;'; ...
    'number_of_vertices = 0;'; ...
    'number_of_triangles = 0;'; ...
    'vertices={'; ...
    '};  // End of vertices for mean mesh'; ...
    'triangles={'; ...
    '};  // End of triangles for mean mesh'; ...
    '}; // End of mean_mesh' }; ...


%-----------Version 1: time consuming 13s
if ~isempty(IndexBegin) && ~isempty(IndexEnd)   
        
    FinalFileHead=TxtFile(1:8,:);   
    
    VerIndex=strmatch('// Pinnacle Treatment Planning System Version', FinalFileHead);
    VerNum=FinalFileHead{VerIndex};
    VerNum=str2num(VerNum(47));
    
    VerEight=0;
    if VerNum > 7
        VerEight=1;
    end
    
    FinalFileMiddle=[];   
    for i=1:RowNum
        if ~isempty(IndexBegin(i))  && ~isempty(IndexEnd(i))
            MiddleTemp=TxtFile(IndexBegin(i)-1:IndexEnd(i), :);
                        
            if VerEight > 0
                TempIndex=strmatch('surface_mesh', MiddleTemp);
                
                %To be adatpive to Jinzhong's mesh reading ROI code
                if ~isempty(TempIndex)
                    FinalFileMiddle=[FinalFileMiddle; MiddleTemp];
                else
                    FinalFileMiddle=[FinalFileMiddle; MiddleTemp(1:end-1); MeshCell; MiddleTemp(end)];
                end
            else
                FinalFileMiddle=[FinalFileMiddle; MiddleTemp];
            end            
        end
    end   
    
    %FinalFile=[FinalFileHead; FinalFileMiddle];
    FinalFile=[FinalFileMiddle];
        
    %Save to locak disk       
    fid=fopen(NewROI, 'w');
    for JJ=1:length(FinalFile)
        fprintf(fid, '%s\n', FinalFile{JJ});
    end
    fclose(fid);
    
end

%Clear ROI file
clear('TxtFile');